### ISSUE TITLE
Variables getting Timer from Planning center online for  on button's?

### ISSUE THREAD

**Issue by Video-PruPru** [bitfocus/companion-module-planningcenter-serviceslive#10]
I was wanting/wondering if it possible to have this?

**Comment by josephdadams** [comment]
I don’t remember for sure if the timer data is in the API or not. I would have to check. But I do know that if we had to pull the API every second or more to get this data and display it on a button, we would get rate limited by PCO.

It might be possible to poll the API every 30 seconds (for example) for the timer data (if it’s included) and then run a local timer in Companion to display instead. Just a thought. But it would only be as accurate as the polling interval because if you advanced PCO Live from somewhere else, the module would not know this until the next poll.

Does this help or make any sense?

**Comment by josephdadams** [comment]
See #3 where someone else asked this awhile back and I forgot 😁
