### ISSUE TITLE
Go to Next Item of Next Plan in Selected Service Type - PCO plan sorting Problem

### ISSUE THREAD

**Issue by sascha9424** [bitfocus/companion-module-planningcenter-serviceslive#7]
There ist a problem with the “Go to Next Item of Next Plan in Selected Service Type”-button. The plans are sorted by months, though not but years. That means, if I use this button right now and I have an existing plan in october but also one in april next year, this button will use the april plan of next year instead of the timewise closer october plan. In the picture you can see that when you use the normal "Go To Next Item"-button and you have to manually select a plan, it is sorting the plans as described above.
I hope this can be fixed as we often have plans of different years at the same time in PCO

**Comment by sascha9424** [comment]
Sry forgot the screenshot: https://ibb.co/7JS8yZr

**Comment by josephdadams** [comment]
I tried to recreate this by adding a plan to one of my service types but for the next year. It was still in the correct sort order. So I suspect the actual problem is that PCO sends the list of plans in their API based on the order you created them in, rather than in month order.

A temporary workaround for you would to be to delete your 2021 plans if there's not too many and recreate them now that your 2020 plans are in place.

**Comment by josephdadams** [comment]
@sascha9424 This is fixed in the latest beta. Go download any build made after this comment.
